# Generated by Django 5.1.7 on 2026-03-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_book_category_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to='core.author'),
        ),
    ]
